language: 
        - cpp

env:
    global:
        - ALPAKA_CI_ANALYSIS=OFF
        - ALPAKA_DEBUG=0
        - ALPAKA_ACC_CPU_B_SEQ_T_SEQ_ENABLE=ON
        - ALPAKA_ACC_CPU_B_SEQ_T_THREADS_ENABLE=ON
        - ALPAKA_ACC_CPU_B_SEQ_T_FIBERS_ENABLE=ON
        - ALPAKA_ACC_CPU_B_TBB_T_SEQ_ENABLE=ON
        - ALPAKA_ACC_CPU_B_OMP2_T_SEQ_ENABLE=ON
        - ALPAKA_ACC_CPU_B_SEQ_T_OMP2_ENABLE=ON
        - ALPAKA_ACC_CPU_BT_OMP4_ENABLE=ON
        - ALPAKA_ACC_GPU_CUDA_ENABLE=OFF
        - ALPAKA_ACC_GPU_CUDA_ONLY_MODE=OFF
        - ALPAKA_CLANG_LIBSTDCPP_VERSION=5
        - CMAKE_VERSION=cmake-3.8.1-Linux-x86_64
os:
    - linux
sudo: required
dist: trusty

compiler:
    - gcc

script:
    - cd utils/
    - git clone https://github.com/ComputationalRadiationPhysics/alpaka.git
    - cd ..
    - mkdir build
    - cd build
    - cmake ..
    - make

before_script:


    - ls ${HOME}/cache
    - sudo apt-get update -qq
    - sudo apt-get install -q -y cmake-data cmake
    - sudo apt-get install -qq build-essential
    - sudo apt-get install -qq libhdf5-dev
    - sudo apt-get install -qq wget
    - gcc --version && g++ --version
    - CMAKE_URL="https://cmake.org/files/v3.8/cmake-3.8.1-Linux-x86_64.tar.gz"
      && mkdir cmake && travis_retry wget --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      && export PATH=${DEPS_DIR}/cmake/bin:${PATH}
             
   
   
