sudo: required

services:
  - docker
language:
  cpp

env:
  - DOCKER_IMG_PATH: Docker/deb
  - DOCKER_IMG_PATH: Docker/ubuntu
script:
  docker build -t ahti  $DOCKER_IMG_NAME $DOCKER_IMG_PATH

notifications: false