language: 
        - cpp

env:
    global:
        - CMAKE_VERSION="cmake-3.8.1-Linux-x86_64"
        - CMAKE_URL="https://cmake.org/files/v3.8/cmake-3.8.1-Linux-x86_64.tar.gz"
        - FFTW_REPO="https://github.com/FFTW/fftw3.git"
        - GTEST_REPO="https://github.com/google/googletest.git"
        - FFTW3_BUILD_FLAGS="--enable-threads --with-openmp --enable-mpi"

# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    # install toolchains
    - gcc-5
    - g++-5

script:
    - cd utils/
    - git clone $GTEST_REPO
    - cd ..
    - mkdir build
    - cd build
    - cmake .. -DTOTEST=Off -DCMAKE_CXX_COMPILER=g++-5 -DCMAKE_C_COMPILER=gcc-5
    - make

before_script:

    - sudo apt-get remove -qq cmake cmake-data
    - sudo apt-get update -y -qq
    - sudo apt-get install -y -qq build-essential
    - sudo apt-get install -y -qq libhdf5-dev
    - sudo apt-get install -y -qq wget
    - sudo apt-get install -y -qq libboost-all-dev cmake-data cmake
    - sudo apt-get install -y -qq openmpi-bin openmpi-doc libopenmpi-dev
    - git clone $FFTW_REP && cd fftw3
    - ./bootstrap.sh
    - ./configure $FFTW3_BUILD_FLAGS
    - make
    - sudo make install
    - cd ..
