language: cpp


os:
    - linux
sudo: required
dist: trusty
compiler:
    - gcc

script:
    - cd utils/
    - git clone https://github.com/ComputationalRadiationPhysics/alpaka.git
    - cd ..
    - mkdir build
    - cd build
    - cmake ..
    - make

before_script:
    - sudo apt-get update -qq
    - sudo apt-get install -q -y cmake-data cmake
    - sudo apt-get install -qq build-essential
    - sudo apt-get install -qq libhdf5-dev
    - gcc --version && g++ --version
    - pwd