language: 
        - cpp

env:
    global:
        - CMAKE_VERSION=cmake-3.8.1-Linux-x86_64
        - CMAKE_URL="https://cmake.org/files/v3.8/cmake-3.8.1-Linux-x86_64.tar.gz"
os:
    - linux
sudo: required
dist: trusty



compiler:
    - gcc
       # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            
script:
    - cd utils/
    - git clone https://github.com/google/googletest.git
    - cd ..
    - mkdir build
    - cd build
    - cmake .. -DTOTEST=Off -DCMAKCE_CXX_COMPLILER=$(which g++-5) -DCMAKE_CC_COMPILER=$(which gcc-5)
    - make

before_script:

    - sudo apt-get remove -qq cmake cmake-data
    - sudo apt-get update -y -qq

    - sudo apt-get install -y -qq build-essential
    - sudo apt-get install -y -qq libhdf5-dev
    - sudo apt-get install -y -qq wget
    - sudo apt-get install -y -qq libboost-all-dev cmake-data cmake
    - sudo apt-get install -y -qq openmpi-bin openmpi-doc libopenmpi-dev
    - sudo apt-get install -y -qq libfftw3-dev
    - gcc --version && g++ --version

