language: cpp


os:
    - linux
sudo: required
dist: trusty
compiler:
    - gcc

script:
    - cd utils/
    - git clone https://github.com/ComputationalRadiationPhysics/alpaka.git
    - cd ..
    - mkdir build
    - cd build
    - cmake ..
    - make

before_script:
    - sudo apt-get update -qq
    - sudo apt-get install -q -y cmake-data cmake
    - sudo apt-get install -qq build-essential
    - sudo apt-get install -qq libhdf5-dev
    - sudo apt-get install -qq wget
    - gcc --version && g++ --version
    - CMAKE_URL="http://www.cmake.org/files/v3.3/cmake-3.3.1-Linux-x86_64.tar.gz"
    - mkdir cmake && travis_retry wget --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
    - export PATH=${DEPS_DIR}/cmake/bin:${PATH}
   
addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data
