sudo: required

services:
  - docker
language:
  cpp

matrix:
  - DOCKER_IMG_PATH: Docker/deb
  - DOCKER_IMG_PATH: Docker/ubuntu
  - DOCKER_IMG_NAME: Ahti
script:
  docker build  $DOCKER_IMG_NAME $DOCKER_IMG_PATH

notifications: false